# Generated by Django 3.2.8 on 2021-10-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=120, null=True)),
                ('kgs_of_beans', models.PositiveSmallIntegerField(null=True)),
                ('Price_per_kg', models.DateField(null=True)),
                ('total_amount', models.CharField(max_length=20, null=True)),
                ('beans_variety', models.PositiveSmallIntegerField(null=True)),
                ('total_quantity_purchased', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
