# Generated by Django 3.2.8 on 2021-10-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='beans_variety',
        ),
    ]
