# Generated by Django 3.2.8 on 2021-10-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_task', '0002_remove_student_beans_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='beans_variety',
            field=models.CharField(choices=[('Female', 'u'), ('male', 'u'), ('none', 'u')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_delivery',
            field=models.DateField(null=True),
        ),
    ]
